.Dd 2025/08/27
.Dt bastille 8
.Os FreeBSD
.Sh NAME
bastille - Bastille is an open-source system for automating deployment
\          and management of containerized applications on FreeBSD.
.Sh SYNOPSIS
.Nm bastille
.Op [option(s)]
.Ar command
.Op [option(s)]
.Ar TARGET
.Ar ARGS
.Sh STARTUP
.Nm To start all containers during boot use:
.Pp
sysrc bastille_enable=YES
.Pp
.Sh SUBCOMMANDS
.Nm The following commands are available:
.Pp
.Bl -tag -width -indent
.It bootstrap
Bootstrap a FreeBSD release for jail base.
.It clone
Clone an existing jail.
.It cmd
Execute arbitrary command on targeted jail(s).
.It config
Get, set or remove a config value for the targeted jail(s).
.It console
Console into a jail.
.It convert
Convert thin jail to thick jail, or convert a jail to a custom release.
.It cp
cp(1) files from host to targeted jail(s).
.It create
Create a jail.
.It destroy
Destroy a jail or release
.It edit
Edit jail configuration files (advanced).
.It export
Exports a jail.
.It help
Help about any command.
.It htop
Interactive process viewer (requires htop).
.It import
Import a jail.
.It jcp
cp(1) files from a jail to jail(s).
.It limits
Apply resources limits to targeted container(s). See rctl(8).
.It list
List jails, releases, templates and more...
.It migrate
Migrate targeted jail(s) to a remote system.
.It mount
Mount a volume inside targeted jail(s).
.It network
Add or remove interfaces from targeted jail(s).
.It pkg
Manipulate binary packages within targeted container(s). See pkg(8).
.It rcp
cp(1) files from a jail to host.
.It rdr
Redirect host port to container port.
.It rename
Rename a jail.
.It restart
Restart a running container.
.It service
Manage services within targeted jail(s).
.It setup
Attempt to auto-configure network, firewall and storage and more...
.It start
Start stopped jail(s).
.It stop
Stop running jail(s).
.It sysrc
Safely edit rc files within targeted jail(s).
.It tags
Add or remove tags to targeted jail(s).
.It template
Apply file templates to targeted jail(s).
.It top
Display and update information about the top(1) cpu processes.
.It umount
Unmount a volume from targeted jail(s).
.It update
Update a jail or release.
.It upgrade
Upgrade a jail to new X.Y-RELEASE.
.It verify
Compare release against a "known good" index.
.It zfs
Manage (get|set) zfs attributes on targeted jail(s).
.El
.Pp
.Sh FILES
.Bl -tag -width "/Users/joeuser/Library/really_long_file_name" -compact
.It Pa /usr/local/bin/bastille
Bastille executable
.El
.Pp
.Sh BUGS
Please report any bugs on Github
.Nm https://github.com/BastilleBSD/bastille/issues
.Pp
.Sh EXAMPLE
bastille bootstrap 12.1-RELEASE
.Pp
bastille create myjail 12.1-RELEASE 10.0.0.1 em0
.Pp
.Nm To create a container with VNET and DHCP use
.Pp
bastille create -V myjail 12.1-RELEASE 0.0.0.0 em0
