.Dd August 20, 2026
.Dt bastille-up 8
.Os
.Sh NAME
.Nm bastille up
.Nd Deploy an OCI jail from a podman-compose.yml file.
.Sh SYNOPSIS
.Nm bastille up
.Op Fl -data-path
.Sh DESCRIPTION
The
.Nm bastille up
sub-command will attempt to parse a podman-compose.yml
file and deploy and services inside it.
.Bl -tag -width Ds
.It Fl -data-path
Override path to persistent data.
.Sh EXAMPLES
.Bl -tag -width Ds
.It Deploy audiobookshelf from /usr/local/projects/audiobookshelf:
.Sy cd /usr/local/projects/audiobookshelf && bastille up
.Sh SEE ALSO
.Xr bastille.conf 5 ,
.Xr bastille-bootstrap 8 ,
.Xr bastille-clone 8 ,
.Xr bastille-cmd 8 ,
.Xr bastille-config 8 ,
.Xr bastille-console 8 ,
.Xr bastille-convert 8 ,
.Xr bastille-cp 8 ,
.Xr bastille-create 8 ,
.Xr bastille-destroy 8 ,
.Xr bastille-edit 8 ,
.Xr bastille-etcupdate 8 ,
.Xr bastille-export 8 ,
.Xr bastille-htop 8 ,
.Xr bastille-import 8 ,
.Xr bastille-jcp 8 ,
.Xr bastille-limits 8 ,
.Xr bastille-list 8 ,
.Xr bastille-logs 8 ,
.Xr bastille-migrate 8 ,
.Xr bastille-monitor 8 ,
.Xr bastille-mount 8 ,
.Xr bastille-network 8 ,
.Xr bastille-pkg 8 ,
.Xr bastille-plugin 8 ,
.Xr bastille-rcp 8 ,
.Xr bastille-rdr 8 ,
.Xr bastille-rename 8 ,
.Xr bastille-restart 8 ,
.Xr bastille-service 8 ,
.Xr bastille-setup 8 ,
.Xr bastille-start 8 ,
.Xr bastille-stop 8 ,
.Xr bastille-sysrc 8 ,
.Xr bastille-tags 8 ,
.Xr bastille-template 8 ,
.Xr bastille-top 8 ,
.Xr bastille-umount 8 ,
.Xr bastille-update 8 ,
.Xr bastille-upgrade 8 ,
.Xr bastille-verify 8 ,
.Xr bastille-zfs 8
