#!/bin/sh

# Bastille Monitor
#
# PROVIDE: bastille_monitor
# REQUIRE: jail
# KEYWORD: shutdown

# Add the following to /etc/rc.conf[.local] to enable this service
#
# bastille_monitor_enable (bool):     Set to "NO" by default.
#                                     Set to "YES" to enable.
# bastille_monitor_rate (bool):       Rate at which to run the monitor.
#                                     Set to "10" by default, 5 minutes.
#

. /etc/rc.subr

name=bastille_monitor
rcvar=${name}_enable

: ${bastille_monitor_enable:="NO"}
: ${bastille_monitor_rate:="10"}

pidfile="/var/run/${name}.pid"
command="/usr/sbin/daemon"
command_args="-R ${bastille_monitor_rate} -P ${pidfile} -H -o /var/log/${name}.log /usr/local/bin/bastille monitor ALL"

load_rc_config ${name}
run_rc_command "$1"
