.Dd 2025/12/06
.Dt bastille-clone 1
.Os
.Sh NAME
.Nm bastille clone
.Nd Clone an existing jail.
.Sh SYNOPSIS
.Nm
.Op Fl alx
.Ar TARGET NEW_NAME IP
.Sh DESCRIPTION
The
.Nm
sub-command will create an exact duplicate of the targeted jail, giving it
the specified
.Ar NEW_NAME
and
.Ar IP
address.
.Bl -tag -width Ds
.It Fl a , Fl -auto
Auto mode. Start/stop jail(s) if required. Cannot be used with [-l|--live].
.It Fl l , Fl -live
Clone a running jail (ZFS only). Cannot be used with [-a|--auto].
.It Fl x , Fl -debug
Enable debug mode.
.Sh EXAMPLES
.Bl -tag -width Ds
.It Clone myjail to newjail:
.Sy bastille clone myjail newjail 10.23.3.4/24
.It Clone myjail to newjail with DHCP (VNET only):
.Sy bastille clone myjail newjail DHCP
.It Clone myjail to newjail while running, with debug mode:
.Sy bastille clone -xl myjail newjail 10.23.3.4/24
.Sh SEE ALSO
.Xr bastille.conf 5 ,
.Xr bastille-bootstrap 1 ,
.Xr bastille-cmd 1 ,
.Xr bastille-config 1 ,
.Xr bastille-console 1 ,
.Xr bastille-convert 1 ,
.Xr bastille-cp 1 ,
.Xr bastille-create 1 ,
.Xr bastille-destroy 1 ,
.Xr bastille-edit 1 ,
.Xr bastille-etcupdate 1 ,
.Xr bastille-export 1 ,
.Xr bastille-htop 1 ,
.Xr bastille-import 1 ,
.Xr bastille-jcp 1 ,
.Xr bastille-limits 1 ,
.Xr bastille-list 1 ,
.Xr bastille-migrate 1 ,
.Xr bastille-mount 1 ,
.Xr bastille-network 1 ,
.Xr bastille-pkg 1 ,
.Xr bastille-rcp 1 ,
.Xr bastille-rdr 1 ,
.Xr bastille-rename 1 ,
.Xr bastille-restart 1 ,
.Xr bastille-service 1 ,
.Xr bastille-setup 1 ,
.Xr bastille-start 1 ,
.Xr bastille-stop 1 ,
.Xr bastille-sysrc 1 ,
.Xr bastille-tags 1 ,
.Xr bastille-template 1 ,
.Xr bastille-top 1 ,
.Xr bastille-umount 1 ,
.Xr bastille-update 1 ,
.Xr bastille-upgrade 1 ,
.Xr bastille-verify 1 ,
.Xr bastille-zfs 1