.Dd 2025/12/06
.Dt bastille-setup 1
.Os
.Sh NAME
.Nm bastille setup
.Nd Auto-configure network, firewall, storage and more...
.Sh SYNOPSIS
.Nm
.Op Fl ax
.Nm
.Op Fl ax
.Ar bridge|linux|loopback|netgraph|firewall|shared|storage|vnet
.Sh DESCRIPTION
The
.Nm
sub-command will attempt to configure different options
for your environment.
.Bl -tag -width Ds
.It Sy bridge
Configure a bride interface for use with the '-B|--bridge' create
option.
.It Sy linux
Configure linux compatability. This involves loading and persisting
some necessary modules, as well as enabling Linux support
with 'linux_enable=YES'.
.It Sy loopback
This will configure an interface to use as a loopback. This is for
NAT jails.
.It Sy netgraph
Configure netgraph for your host. This requires loading and
persisting certain 'netgraph_*' modules.
.It Sy firewall
Configure the 'pf' firewall for use with NAT jails, as well
as the 'rdr' sub-command. See
.Xr bastille-rdr 1 .
.It Sy shared
Configure a 'shared' interface. This is essentially an interface
where jails will 'share' with the host, while still having
their own locally reachable IP.
.It Sy storage
Configure storage (ZFS or UFS).
.It Sy vnet
Configure your host to be able to use VNET jails.
.It Fl y , -yes
Do not prompt. Assume always yes.
.It Fl x , -debug
Enable debug mode.
.El
.Pp
The 'loopback' and 'shared' options will de-configure each other when
they are configured. The INTERFACE these options configure are
only ever used when the INTERFACE argument is not specified
during jail creation.
.Sh EXAMPLES
.Bl -tag -width Ds
.It Setup Bastille for the first time:
.Sy bastille setup
.It Setup Linux support:
.Sy bastille setup linux
.It Setup a bridge:
.Sy bastille setup bridge
.Sh SEE ALSO
.Xr bastille.conf 5 ,
.Xr bastille-bootstrap 1 ,
.Xr bastille-clone 1 ,
.Xr bastille-cmd 1 ,
.Xr bastille-config 1 ,
.Xr bastille-console 1 ,
.Xr bastille-convert 1 ,
.Xr bastille-cp 1 ,
.Xr bastille-create 1 ,
.Xr bastille-destroy 1 ,
.Xr bastille-edit 1 ,
.Xr bastille-etcupdate 1 ,
.Xr bastille-export 1 ,
.Xr bastille-htop 1 ,
.Xr bastille-import 1 ,
.Xr bastille-jcp 1 ,
.Xr bastille-limits 1 ,
.Xr bastille-list 1 ,
.Xr bastille-migrate 1 ,
.Xr bastille-mount 1 ,
.Xr bastille-network 1 ,
.Xr bastille-pkg 1 ,
.Xr bastille-rcp 1 ,
.Xr bastille-rdr 1 ,
.Xr bastille-rename 1 ,
.Xr bastille-restart 1 ,
.Xr bastille-service 1 ,
.Xr bastille-start 1 ,
.Xr bastille-stop 1 ,
.Xr bastille-sysrc 1 ,
.Xr bastille-tags 1 ,
.Xr bastille-template 1 ,
.Xr bastille-top 1 ,
.Xr bastille-umount 1 ,
.Xr bastille-update 1 ,
.Xr bastille-upgrade 1 ,
.Xr bastille-verify 1 ,
.Xr bastille-zfs 1