.Dd 2025/12/04
.Dt bastille 1
.Os
.Sh NAME
.Nm bastille
.Nd open-source jail automation and management tool
.Sh SYNOPSIS
.Nm
.Op Fl vh
.Op Fl c Ar file
.Ar COMMAND
.Op option(s)
.Ar TARGET
.Ar ARGS
.Sh DESCRIPTION
Bastille is an open-source system for automating deployment
and management of containerized applications on FreeBSD
using the jail framework.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl c Ar file , Fl -config Ar file
Specify a non-default config file to use. Must be placed
inside the Bastille config directory.
.It Fl h , Fl -help
Display usage information. This option is also available for each
sub-command, though they are not listed in the man pages.
.It Fl v , Fl -version
Print version information.
.Sh SUBCOMMANDS
.Bl -tag -width Ds
.It Sy bootstrap
Bootstrap a release or template(s).
.It Sy clone
Clone an existing jail.
.It Sy cmd
Execute arbitrary command on targeted jail(s).
.It Sy config
Get, set, add or remove properties from targeted jail(s).
.It Sy console
Console into a jail.
.It Sy convert
Convert thin jail to thick jail, or convert a jail to a custom release.
.It Sy cp
cp(1) files from host to targeted jail(s).
.It Sy create
Create a jail.
.It Sy destroy
Destroy a jail or release
.It Sy edit
Edit jail configuration files (advanced).
.It Sy export
Exports a jail.
.It Sy help
Help about any command.
.It Sy htop
Interactive process viewer (requires htop).
.It Sy import
Import a jail.
.It Sy jcp
cp(1) files from a jail to jail(s).
.It Sy limits
Apply resources limits to targeted container(s). See rctl(8).
.It Sy list
List jails, releases, templates and more...
.It Sy migrate
Migrate targeted jail(s) to a remote system.
.It Sy mount
Mount a volume inside targeted jail(s).
.It Sy network
Add or remove interfaces from targeted jail(s).
.It Sy pkg
Manipulate binary packages within targeted container(s). See pkg(8).
.It Sy rcp
cp(1) files from a jail to host.
.It Sy rdr
Redirect host port to container port.
.It Sy rename
Rename a jail.
.It Sy restart
Restart a running container.
.It Sy service
Manage services within targeted jail(s).
.It Sy setup
Attempt to auto-configure network, firewall and storage and more...
.It Sy start
Start stopped jail(s).
.It Sy stop
Stop running jail(s).
.It Sy sysrc
Safely edit rc files within targeted jail(s).
.It Sy tags
Add or remove tags to targeted jail(s).
.It Sy template
Apply file templates to targeted jail(s).
.It Sy top
Display and update information about the top(1) cpu processes.
.It Sy umount
Unmount a volume from targeted jail(s).
.It Sy update
Update a jail or release.
.It Sy upgrade
Upgrade a jail to new X.Y-RELEASE.
.It Sy verify
Compare release against a "known good" index.
.It Sy zfs
Manage (get|set) zfs attributes on targeted jail(s).
.Sh SEE ALSO
.Xr bastille.conf 5
.Xr bastille-bootstrap 1
.Xr bastille-clone 1
.Xr bastille-cmd 1
.Xr bastille-config 1
.Xr bastille-console 1
.Xr bastille-convert 1
.Xr bastille-cp 1
.Xr bastille-create 1
.Xr bastille-destroy 1
.Xr bastille-edit 1
.Xr bastille-etcupdate 1
.Xr bastille-export 1
.Xr bastille-htop 1
.Xr bastille-import 1
.Xr bastille-jcp 1
.Xr bastille-limits 1
.Xr bastille-list 1
.Xr bastille-migrate 1
.Xr bastille-mount 1
.Xr bastille-network 1
.Xr bastille-pkg 1
.Xr bastille-rcp 1
.Xr bastille-rdr 1
.Xr bastille-rename 1
.Xr bastille-restart 1
.Xr bastille-service 1
.Xr bastille-setup 1
.Xr bastille-start 1
.Xr bastille-stop 1
.Xr bastille-sysrc 1
.Xr bastille-tags 1
.Xr bastille-top 1
.Xr bastille-umount 1
.Xr bastille-update 1
.Xr bastille-upgrade 
.Xr bastille-verify 1
.Xr bastille-zfs 1
.Sh BUGS
Please report any bugs on Github
.Nm https://github.com/BastilleBSD/bastille/issues
