.Dd 2025/12/06
.Dt bastille-template 1
.Os
.Sh NAME
.Nm bastille template
.Nd Apply templates to jail(s).
.Sh SYNOPSIS
.Nm
.Op Fl ax
.Ar TARGET|convert TEMPLATE
.Sh DESCRIPTION
The
.Nm
sub-command will apply the specified
.Ar TEMPLATE
to
.Ar TARGET .
.Bl -tag -width Ds
.It Fl a , Fl -auto
Auto mode. Start/stop jail(s) if required.
.It Fl x , -debug
Enable debug mode.
.El
.Pp
The
.Ar convert
option is only to convert older style templates to the
new format, which consists of a single 'Bastillefile' inside
'project/template'.
.Sh EXAMPLES
.Bl -tag -width Ds
.It Apply www/nginx to myjail:
.Sy bastille template myjail www/nginx
.Sh SEE ALSO
.Xr bastille.conf 5 ,
.Xr bastille-bootstrap 1 ,
.Xr bastille-clone 1 ,
.Xr bastille-cmd 1 ,
.Xr bastille-config 1 ,
.Xr bastille-console 1 ,
.Xr bastille-convert 1 ,
.Xr bastille-cp 1 ,
.Xr bastille-create 1 ,
.Xr bastille-destroy 1 ,
.Xr bastille-edit 1 ,
.Xr bastille-etcupdate 1 ,
.Xr bastille-export 1 ,
.Xr bastille-htop 1 ,
.Xr bastille-import 1 ,
.Xr bastille-jcp 1 ,
.Xr bastille-limits 1 ,
.Xr bastille-list 1 ,
.Xr bastille-migrate 1 ,
.Xr bastille-mount 1 ,
.Xr bastille-network 1 ,
.Xr bastille-pkg 1 ,
.Xr bastille-rcp 1 ,
.Xr bastille-rdr 1 ,
.Xr bastille-rename 1 ,
.Xr bastille-restart 1 ,
.Xr bastille-service 1 ,
.Xr bastille-setup 1 ,
.Xr bastille-start 1 ,
.Xr bastille-stop 1 ,
.Xr bastille-sysrc 1 ,
.Xr bastille-tags 1 ,
.Xr bastille-top ,
.Xr bastille-umount 1 ,
.Xr bastille-update 1 ,
.Xr bastille-upgrade 1 ,
.Xr bastille-verify 1 ,
.Xr bastille-zfs 1