.Dd 2025/12/06
.Dt bastille-rdr 1
.Os
.Sh NAME
.Nm bastille rdr
.Nd Redirect host port to jail port.
.Sh SYNOPSIS
.Nm
.Op Fl x
.Op Fl d Ar IP
.Op Fl i Ar INTERFACE
.Op Fl s Ar IP|TABLE
.Op Fl t Ar ipv4|ipv6
.Ar TARGET Sy tcp|udp Ar HOST_PORT JAIL_PORT Op log LOG_OPTIONS
.Nm
.Op Fl x
.Ar TARGET Sy clear|reset|list
.Sh DESCRIPTION
The
.Nm
sub-command will redirect
.Ar HOST_PORT
to
.Ar JAIL_PORT .
.Bl -tag -width Ds
.It Sy bastille rdr Oo Fl x Oc Oo Fl d Ar IP Oc Oo Fl i Ar INTERFACE Oc Oo Fl s Ar IP|TABLE Oc Oo Fl t Ar ipv4|ipv6 Oc Sy add Ar tcp|udp HOST_PORT JAIL_PORT Op log LOG_OPTIONS
.Bl -tag -width Ds
.It Sy add
Add the rdr rule to the jail.
.It Fl d Ar IP , Fl -destination Ar IP
Limit rdr to a destination IP.
.It Fl i Ar INTERFACE , Fl -interface Ar INTERFACE
Specify interface(s) to apply rule to. Comma-separated.
.It Fl s Ar IP|TABLE , Fl -source Ar IP|TABLE
Limit rdr to a source IP or table.
.Pp
The table should exist in your 'pf.conf'.
.It Fl t Ar ipv4|ipv6 , Fl -type Ar ipv4|ipv6
Specify IP type. Must be used if '-s' or '-d' are used. Defaults to both.
.It Fl x , Fl -debug
Enable debug mode.
.El
.It Sy bastille rdr Oo Fl x Oc Sy clear|reset|list 
.Bl -tag -width Ds
.It Sy clear
Clear the rules from the system, but don't remove from the jail
configuration.
.It Sy reset
Clear the rules from the system, and remove from the jail
configuration.
.It Sy list
List active rules.
.Ar INTERFACE
from the jail.
.It Fl x , Fl -debug
Enable debug mode.
.Sh EXAMPLES
.Bl -tag -width Ds
.It Forward port 80 from host to myjail:
.Sy bastille rdr myjail tcp 80 80
.It Forward port 80 from host to myjail on vtnet0:
.Sy bastille rdr -i vtnet0 myjail tcp 80 80
.It Forward port 80 from host to myjail, limiting to 200.200.200.200:
.Sy bastille rdr -s 200.200.200.200 myjail tcp 80 80
.Sh SEE ALSO
.Xr bastille.conf 5 ,
.Xr bastille-bootstrap 1 ,
.Xr bastille-clone 1 ,
.Xr bastille-cmd 1 ,
.Xr bastille-config 1 ,
.Xr bastille-console 1 ,
.Xr bastille-convert 1 ,
.Xr bastille-cp 1 ,
.Xr bastille-create 1 ,
.Xr bastille-destroy 1 ,
.Xr bastille-edit 1 ,
.Xr bastille-etcupdate 1 ,
.Xr bastille-export 1 ,
.Xr bastille-htop 1 ,
.Xr bastille-import 1 ,
.Xr bastille-jcp 1 ,
.Xr bastille-limits 1 ,
.Xr bastille-list 1 ,
.Xr bastille-migrate 1 ,
.Xr bastille-mount 1 ,
.Xr bastille-network 1 ,
.Xr bastille-pkg 1 ,
.Xr bastille-rcp 1 ,
.Xr bastille-rename 1 ,
.Xr bastille-restart 1 ,
.Xr bastille-service 1 ,
.Xr bastille-setup 1 ,
.Xr bastille-start 1 ,
.Xr bastille-stop 1 ,
.Xr bastille-sysrc 1 ,
.Xr bastille-tags 1 ,
.Xr bastille-template 1 ,
.Xr bastille-top 1 ,
.Xr bastille-umount 1 ,
.Xr bastille-update 1 ,
.Xr bastille-upgrade 1 ,
.Xr bastille-verify 1 ,
.Xr bastille-zfs 1