.Dd 2025/12/06
.Dt bastille-destroy 1
.Os
.Sh NAME
.Nm bastille destroy
.Nd Destroy jail(s) or release(s). 
.Sh SYNOPSIS
.Nm
.Op Fl ayx
.Ar JAIL
.Nm
.Op Fl cfx
.Ar RELEASE
.Sh DESCRIPTION
The
.Nm
sub-command is used to destroy jails or releases.
.Bl -tag -width Ds
.It Sy destroy Oo Fl ayx Oc Ar JAIL
.Bl -tag -width Ds
.It Fl a , Fl -auto
Auto mode. Start/stop jail(s) if required.
.It Fl y , Fl -yes
Do no prompt. Assume always yes.
.Pp
By default Bastille will ask
if you are sure you want to destroy the jail. Set this option
to bypass these prompts.
.It Fl x , -debug
Enable debug mode.
.El
.It Sy destroy Oo Fl cfx Oc Ar RELEASE
.Bl -tag -width Ds
.It Fl c , Fl -no-cache
Do not destroy cache when destroying release (legacy releases).
.Pp
This does not apply
to PkgBase releases. Cache are the '.txz' dist files downloaded
during the 'bootstrap' phase.
.It Fl f , Fl -force
Force unmount any mounted datasets when destroying a jail or
release (ZFS only).
.Sh EXAMPLES
.Bl -tag -width Ds
.It Destroy 15.0-RELEASE:
.Sy bastille destroy 15.0-RELEASE
.It Destroy myjail forcibly, without prompts, and auto mode:
.Sy bastille destroy -afy myjail
.It Destroy myjail and yourjail:
.Sy bastille destroy 'myjail yourjail'
.Sh SEE ALSO
.Xr bastille.conf 5 ,
.Xr bastille-bootstrap 1 ,
.Xr bastille-clone 1 ,
.Xr bastille-cmd 1 ,
.Xr bastille-config 1 ,
.Xr bastille-console 1 ,
.Xr bastille-convert 1 ,
.Xr bastille-cp 1 ,
.Xr bastille-create 1 ,
.Xr bastille-edit 1 ,
.Xr bastille-etcupdate 1 ,
.Xr bastille-export 1 ,
.Xr bastille-htop 1 ,
.Xr bastille-import 1 ,
.Xr bastille-jcp 1 ,
.Xr bastille-limits 1 ,
.Xr bastille-list 1 ,
.Xr bastille-migrate 1 ,
.Xr bastille-mount 1 ,
.Xr bastille-network 1 ,
.Xr bastille-pkg 1 ,
.Xr bastille-rcp 1 ,
.Xr bastille-rdr 1 ,
.Xr bastille-rename 1 ,
.Xr bastille-restart 1 ,
.Xr bastille-service 1 ,
.Xr bastille-setup 1 ,
.Xr bastille-start 1 ,
.Xr bastille-stop 1 ,
.Xr bastille-sysrc 1 ,
.Xr bastille-tags 1 ,
.Xr bastille-template 1 ,
.Xr bastille-top 1 ,
.Xr bastille-umount 1 ,
.Xr bastille-update 1 ,
.Xr bastille-upgrade 1 ,
.Xr bastille-verify 1 ,
.Xr bastille-zfs 1