name: ShellCheck Linting

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Run ShellCheck
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
        env:
          # Excluding SC3043: In POSIX sh, 'local' is undefined. Ignoring because local is a built-in command in FreeBSD
          # Excluding SC2154: Variable is referenced but not assigned. Because we include files in the scripts
          # Excluding SC3037: In POSIX sh, echo flags are undefined. Ignoring temporarily until we decide to keep it or
          #                   use printf instead
          SHELLCHECK_OPTS: -e SC3043 -e SC2154 -e SC3037
        with:
          severity: warning
          scandir: "./usr/local/share/bastille"
          additional_files: "./usr/local/bin/bastille"
          ignore_paths: "./usr/local/share/bastille/templates ./usr/local/share/bastille/colors.pre.sh"
